name: build_and_push
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v2
      
    # build and publish image
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: marshians/arch-repo
        tags: latest
